---
- name: Install Docker Engine
  hosts: webserver
  become: true

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key (for Debian/Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (for Debian/Ubuntu)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker Engine (for Debian/Ubuntu)
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'
'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the current user to the docker group
      user:
        name: "{{ ansibleadmin }}"
        groups: docker
        append: yes
        state: present

  handlers:
    - name: Restart Docker service
      systemd:
         name: docker
         state: restarted

