---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'