---
- name: Install Docker Engine
  hosts: webserver
  become: true

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key (for Debian/Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository (for Debian/Ubuntu)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker Engine (for Debian/Ubuntu)
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install required packages (for CentOS/RHEL)
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add Docker repository (for CentOS/RHEL)
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_os_family == 'RedHat'

    - name: Install Docker Engine (for CentOS/RHEL)
      yum:
        name: docker-ce
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the current user to the docker group
      user:
        name: "{{ ansibleadmin }}"
        groups: docker
        append: yes
        state: present

  handlers:
    - name: Restart Docker service
      service:
        name: docker
        state: restarted
